config/routes.rb
Prash::Application.routes.draw do
  get "store/search"

  get "stores/search"

  devise_for :users, :path => '', :path_names => {:sign_in => '/admin/sign_in'}
  resources :orders do
    collection do
      post 'post_back'
    end
  end
  resources :terms
  resources :location_types

  resources :cities do
    collection do
      get 'load_city'
    end
  end

  resources :states do
    collection do
      get 'load_state'
    end
  end
  resources :countries
  resources :locations
  resources :areas do
    collection do
      get 'load_area'
    end
  end

  resources :stores do
    collection do
      get 'search'
    end
  end

# The priority is based upon orders of creation:
# first created -> highest priority.

# Sample of regular route:
#   match 'products/:id' => 'catalog#view'
# Keep in mind you can assign values other than :controller and :action

# Sample of named route:
#   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
# This route can be invoked with purchase_url(:id => product.id)

# Sample resource route (maps HTTP verbs to controller actions automatically):
#   resources :products

# Sample resource route with options:
#   resources :products do
#     member do
#       get 'short'
#       post 'toggle'
#     end
#
#     collection do
#       get 'sold'
#     end
#   end

# Sample resource route with sub-resources:
#   resources :products do
#     resources :comments, :sales
#     resource :seller
#   end

# Sample resource route with more complex sub-resources
#   resources :products do
#     resources :comments
#     resources :sales do
#       get 'recent', :on => :collection
#     end
#   end

# Sample resource route within a namespace:
#   namespace :admin do
#     # Directs /admin/products/* to Admin::ProductsController
#     # (app/controllers/admin/products_controller.rb)
#     resources :products
#   end

# You can have the root of your site routed with "root"
# just remember to delete public/index.html.
  root :to => 'welcome#index'

# See how all your routes lay out with "rake routes"

# This is a legacy wild controller route that's not recommended for RESTful applications.
# Note: This route will make all actions in every controller accessible via GET requests.
  match ':controller(/:action(/:id))(.:format)'
end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :country_id, :name

  has_many :cities
  has_many :locations
  belongs_to :country

  validates :name, presence: true
  validates :country_id, presence: true

  scope :by_country, ->(country_id) { where(country_id: country_id) }
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  def index
    @states = State.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @states }
    end
  end

  def show
    @state = State.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @state }
    end
  end

  def new
    @state = State.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @state }
    end
  end

  def edit
    @state = State.find(params[:id])
  end

  def create
    @state = State.new(params[:state])

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render json: @state, status: :created, location: @state }
      else
        format.html { render action: "new" }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @state = State.find(params[:id])

    respond_to do |format|
      if @state.update_attributes(params[:state])
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  def load_state
    @states = State.by_country(params[:country])
    @cities = City.by_country(params[:country])

    states = @states.collect do |state|
      {id: state.id, name: state.name}
    end

    cities = @cities.collect do |city|
      {id: city.id, name: city.name}
    end

    result = {states: states, cities: cities}

    render json: result
  end

  def destroy
    @state = State.find(params[:id])
    @state.destroy

    respond_to do |format|
      format.html { redirect_to states_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.erb
<div class="row">
  <div class="col-lg-4">
    <%= form_for(@state) do |f| %>
        <% if @state.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>

              <ul>
                <% @state.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="form-group">
          <%= f.label :name %>
          <br/>
          <%= f.text_field :name, :class => "form-control"  %>
        </div>
        <div class="form-group">
          <%= f.label :country_id %>
          <br/>
          <%= select :state, :country_id, Country.all.collect { |c| [c.name, c.id] }, {:prompt => 'Select Country'}, {:class => 'form-control'} %>
        </div>
        <div class="form-actions">
          <%= f.submit %>
        </div>
    <% end %>
  </div>
</div>

app/views/states/edit.html.erb
<h1>Editing state</h1>

<%= render 'form' %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<div class="row">
  <div class="col-lg-7">
    <h2>States</h2>

    <div class="table-responsive">
      <table class="table table-bordered table-hover ">
        <thead>
        <tr>
          <th>Name</th>
          <th>Country</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <% @states.each do |state| %>
            <tr>
              <td><%= state.name %></td>
              <td><%= state.try(:country).try(:name) %></td>
              <td><%= link_to 'Show', state %></td>
              <td><%= link_to 'Edit', edit_state_path(state) %></td>
              <td><%= link_to 'Destroy', state, method: :delete, data: {confirm: 'Are you sure?'} %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <%= link_to 'New State', new_state_path %>
  </div>
</div><!-- /.row -->

app/views/states/new.html.erb
<h1>New state</h1>

<%= render 'form' %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @state.name %>
</p>

<p>
  <b>Country:</b>
  <%= @state.country_id %>
</p>


<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>