config/routes.rb
Prash::Application.routes.draw do
  get "store/search"

  get "stores/search"

  devise_for :users, :path => '', :path_names => {:sign_in => '/admin/sign_in'}
  resources :orders do
    collection do
      post 'post_back'
    end
  end
  resources :terms
  resources :location_types

  resources :cities do
    collection do
      get 'load_city'
    end
  end

  resources :states do
    collection do
      get 'load_state'
    end
  end
  resources :countries
  resources :locations
  resources :areas do
    collection do
      get 'load_area'
    end
  end

  resources :stores do
    collection do
      get 'search'
    end
  end

# The priority is based upon orders of creation:
# first created -> highest priority.

# Sample of regular route:
#   match 'products/:id' => 'catalog#view'
# Keep in mind you can assign values other than :controller and :action

# Sample of named route:
#   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
# This route can be invoked with purchase_url(:id => product.id)

# Sample resource route (maps HTTP verbs to controller actions automatically):
#   resources :products

# Sample resource route with options:
#   resources :products do
#     member do
#       get 'short'
#       post 'toggle'
#     end
#
#     collection do
#       get 'sold'
#     end
#   end

# Sample resource route with sub-resources:
#   resources :products do
#     resources :comments, :sales
#     resource :seller
#   end

# Sample resource route with more complex sub-resources
#   resources :products do
#     resources :comments
#     resources :sales do
#       get 'recent', :on => :collection
#     end
#   end

# Sample resource route within a namespace:
#   namespace :admin do
#     # Directs /admin/products/* to Admin::ProductsController
#     # (app/controllers/admin/products_controller.rb)
#     resources :products
#   end

# You can have the root of your site routed with "root"
# just remember to delete public/index.html.
  root :to => 'welcome#index'

# See how all your routes lay out with "rake routes"

# This is a legacy wild controller route that's not recommended for RESTful applications.
# Note: This route will make all actions in every controller accessible via GET requests.
  match ':controller(/:action(/:id))(.:format)'
end

app/models/area.rb
class Area < ActiveRecord::Base
  attr_accessible :name, :city_id
  belongs_to :city
  has_many :locations

  validates :name, presence: true
  validates :city_id, presence: true

  scope :by_city, ->(city_id) { where(city_id: city_id) }
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  def index
    @areas = Area.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @areas }
    end
  end

  def show
    @area = Area.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @area }
    end
  end

  def new
    @area = Area.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @area }
    end
  end

  def edit
    @area = Area.find(params[:id])
  end

  def create
    @area = Area.new(params[:area])

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render json: @area, status: :created, location: @area }
      else
        format.html { render action: "new" }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @area = Area.find(params[:id])

    respond_to do |format|
      if @area.update_attributes(params[:area])
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  def load_area
    @areas = Area.by_city(params[:city])

    result = @areas.collect do |area|
      {id: area.id, name: area.name}
    end

    render json: result
  end

  def destroy
    @area = Area.find(params[:id])
    @area.destroy

    respond_to do |format|
      format.html { redirect_to areas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.erb
<div class="row">
  <div class="col-lg-4">
    <%= form_for(@area) do |f| %>
        <% if @area.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@area.errors.count, "error") %> prohibited this area from being saved:</h2>

              <ul>
                <% @area.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="form-group">
          <%= f.label :name %>
          <br/>
          <%= f.text_field :name, :class => "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :city_id %>
          <br/>
          <%= select :area, :city_id, City.all.collect { |c| [c.name, c.id] }, {:prompt => 'Select City'}, {:class => 'form-control'} %>
        </div>
        <div class="form-actions">
          <%= f.submit %>
        </div>
    <% end %>
  </div>
</div>

app/views/areas/edit.html.erb
<h1>Editing area</h1>

<%= render 'form' %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

app/views/areas/index.html.erb
<div class="row">
  <div class="col-lg-7">
    <h2>Areas</h2>
    <div class="table-responsive">
      <table class="table table-bordered table-hover ">
        <thead>
        <tr>
          <th>Name </th>
          <th>City </th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <% @areas.each do |area| %>
            <tr>
              <td><%= area.name %></td>
              <td><%= area.try(:city).try(:name) %></td>
              <td><%= link_to 'Show', area %></td>
              <td><%= link_to 'Edit', edit_area_path(area) %></td>
              <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <%= link_to 'New Area', new_area_path %>
  </div>
</div><!-- /.row -->

app/views/areas/new.html.erb
<h1>New area</h1>

<%= render 'form' %>

<%= link_to 'Back', areas_path %>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @area.name %>
</p>


<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>