config/routes.rb
Prash::Application.routes.draw do
  get "store/search"

  get "stores/search"

  devise_for :users, :path => '', :path_names => {:sign_in => '/admin/sign_in'}
  resources :orders do
    collection do
      post 'post_back'
    end
  end
  resources :terms
  resources :location_types

  resources :cities do
    collection do
      get 'load_city'
    end
  end

  resources :states do
    collection do
      get 'load_state'
    end
  end
  resources :countries
  resources :locations
  resources :areas do
    collection do
      get 'load_area'
    end
  end

  resources :stores do
    collection do
      get 'search'
    end
  end

# The priority is based upon orders of creation:
# first created -> highest priority.

# Sample of regular route:
#   match 'products/:id' => 'catalog#view'
# Keep in mind you can assign values other than :controller and :action

# Sample of named route:
#   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
# This route can be invoked with purchase_url(:id => product.id)

# Sample resource route (maps HTTP verbs to controller actions automatically):
#   resources :products

# Sample resource route with options:
#   resources :products do
#     member do
#       get 'short'
#       post 'toggle'
#     end
#
#     collection do
#       get 'sold'
#     end
#   end

# Sample resource route with sub-resources:
#   resources :products do
#     resources :comments, :sales
#     resource :seller
#   end

# Sample resource route with more complex sub-resources
#   resources :products do
#     resources :comments
#     resources :sales do
#       get 'recent', :on => :collection
#     end
#   end

# Sample resource route within a namespace:
#   namespace :admin do
#     # Directs /admin/products/* to Admin::ProductsController
#     # (app/controllers/admin/products_controller.rb)
#     resources :products
#   end

# You can have the root of your site routed with "root"
# just remember to delete public/index.html.
  root :to => 'welcome#index'

# See how all your routes lay out with "rake routes"

# This is a legacy wild controller route that's not recommended for RESTful applications.
# Note: This route will make all actions in every controller accessible via GET requests.
  match ':controller(/:action(/:id))(.:format)'
end

app/controllers/location_types_controller.rb
class LocationTypesController < ApplicationController
  def index
    @location_types = LocationType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @location_types }
    end
  end

  def show
    @location_type = LocationType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location_type }
    end
  end

  def new
    @location_type = LocationType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location_type }
    end
  end

  def edit
    @location_type = LocationType.find(params[:id])
  end

  def create
    @location_type = LocationType.new(params[:location_type])

    respond_to do |format|
      if @location_type.save
        format.html { redirect_to @location_type, notice: 'Location type was successfully created.' }
        format.json { render json: @location_type, status: :created, location: @location_type }
      else
        format.html { render action: "new" }
        format.json { render json: @location_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @location_type = LocationType.find(params[:id])

    respond_to do |format|
      if @location_type.update_attributes(params[:location_type])
        format.html { redirect_to @location_type, notice: 'Location type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @location_type = LocationType.find(params[:id])
    @location_type.destroy

    respond_to do |format|
      format.html { redirect_to location_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/location_types_helper.rb
module LocationTypesHelper
end

app/views/location_types/_form.html.erb
<div class="row">
  <div class="col-lg-4">
    <%= form_for(@location_type) do |f| %>
        <% if @location_type.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@location_type.errors.count, "error") %> prohibited this location_type from being
                saved:</h2>

              <ul>
                <% @location_type.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="form-group">
          <%= f.label :name %>
          <br/>
          <%= f.text_field :name, :class => "form-control" %>
        </div>
        <div class="form-actions">
          <%= f.submit %>
        </div>
    <% end %>
  </div>
</div>

app/views/location_types/edit.html.erb
<h1>Editing location_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @location_type %> |
<%= link_to 'Back', location_types_path %>

app/views/location_types/index.html.erb
<div class="row">
  <div class="col-lg-7">
    <h2>Location Types</h2>

    <div class="table-responsive">
      <table class="table table-bordered table-hover ">
        <thead>
        <tr>
          <th>Name</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <% @location_types.each do |location_type| %>
            <tr>
              <td><%= location_type.name %></td>
              <td><%= link_to 'Show', location_type %></td>
              <td><%= link_to 'Edit', edit_location_type_path(location_type) %></td>
              <td><%= link_to 'Destroy', location_type, method: :delete, data: {confirm: 'Are you sure?'} %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <%= link_to 'New Location type', new_location_type_path %>
  </div>
</div><!-- /.row -->

app/views/location_types/new.html.erb
<h1>New Location Type</h1>

<%= render 'form' %>

<%= link_to 'Back', location_types_path %>

app/views/location_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @location_type.name %>
</p>


<%= link_to 'Edit', edit_location_type_path(@location_type) %> |
<%= link_to 'Back', location_types_path %>